# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu"];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems =[ "ntfs" ];
  hardware.enableRedistributableFirmware = true;                                                                                                                                                                   
  hardware.graphics ={
    enable = true;
    enable32Bit = true;
  };
  hardware.amdgpu.amdvlk = {
        enable = true;
        support32Bit.enable = true;
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9cb85c8d-bdc8-422e-92ce-38ea402923f5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FF96-40FC";
      fsType = "vfat";
    };

  fileSystems."/home/nakul/windir" = {
      device = "/dev/sda1";
      fsType = "ntfs-3g";
      options = ["rw" "uid=1000" ];
  };
  fileSystems."/home/nakul/game-drive" = {
      device = "/dev/nvme0n1p2";
      fsType = "ntfs-3g";
      options = ["rw" "uid=1000" ];
  };
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
